name: Crawl for Course programmes

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:
  schedule:
    # “At 00:00 on day-of-month 15 in every 3rd month.”
    - cron: "0 0 15 */3 *"

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Archived Courses (Automated)
      CI_COMMIT_AUTHOR: Course Crawler Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install requests pandas tqdm lxml html5lib

      - name: Fetch Course programme
        run: python yum.py # This script is expected to make changes in ./public/

      - name: Commit and Push to repo
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"

          git add ./public/

          if ! git diff --staged --quiet; then
            echo "Changes detected in ./public/, committing..."
            git commit -m "${{ env.CI_COMMIT_MESSAGE }} (before rebase)"
          else
            echo "No changes in ./public/ to commit."
          fi

          echo "Pulling from origin main with rebase..."
          git pull --rebase origin main

          echo "Pushing to origin main..."
          git push origin main
